_BASE_: '../Base-RCNN-FPN-KINS.yaml'
OUTPUT_DIR: ../data/train_outputs/aisformer/aisformer_R_50_FPN_1x_amodal_kins/
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_MASK_HEAD:
    CUSTOM_NAME: AISFormer
TEST:
  EVAL_PERIOD: 1
